metadata:
  servicename: server
server:
  host: localhost
  port: 5000
otel:
  log:
    level: info
    development: false
  trace:
    proto: grpc
    endpoint: localhost:30800
  # metric:
  #   proto: grpc
  #   endpoint: localhost:30800
db:
  dsn: "postgres://postgres:my-secret-pw@localhost:5432/testfsd"
rabbitmq:
  dsn: "amqp://guest:guest@localhost:5672/"